name: WoW Packager
description: Build and publish World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  args:
    description: 'Command-line arguments. See https://github.com/BigWigsMods/packager#usage'
    required: false
  pandoc:
    description: 'Install pandoc before packaging if uploading to WoWInterface.'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - run: INPUT_PANDOC=${{ inputs.pandoc }} $GITHUB_ACTION_PATH/setup-packager.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
